services:
  dev-db:
    image: postgres:13
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    networks:
      - assign

  test-db:
    image: postgres:13
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - test-db-data:/var/lib/postgresql/data
    networks:
      - assign

networks: 
  assign:

volumes:
  dev-db-data:
  test-db-data:
